### ISSUE TITLE
SkipTLS option limited to source configuration

### ISSUE THREAD

**Issue by shimish2** [anuvu/stacker#106]
When we set SkipTLS to be true in ImageCopyOpts, only source context is configured to work according to that. There is also possibility that we need to skip destination tls verification.

**Comment by tych0** [comment]
Seems very reasonable to skip the destination as well, I just never had a use for it. Feel free to send a patch!

**Comment by tych0** [comment]
Maybe we need SkipSourceTLS and SkipDestTLS

**Comment by shimish2** [comment]
Yes, will do
