### ISSUE TITLE
make build-multiple build things in a deterministic order

### ISSUE THREAD

**Issue by raharper** [anuvu/stacker#124]
stacker recursive-build does a great job of finding dependencies but it does not always build the layers in the same order.  This is only observed either through careful inspection of the output, or if there are errors, a second run may reproduce different error due to the change in build order.

**Comment by tych0** [comment]
golang randomizes map orders, which is my best guess about where the source of this is. stuff like the dag code: https://github.com/anuvu/stacker/blob/master/lib/dag.go#L69 uses maps, and is also used to resolve what order to build things in.

Individual stacker files have a bunch of code that takes care to try and build things in the order they're in the file, so perhaps we can steal that approach somehow: https://github.com/anuvu/stacker/blob/master/types/stackerfile.go#L181
