### ISSUE TITLE
speed up stacker import hashing

### ISSUE THREAD

**Issue by tych0** [anuvu/stacker#210]
It seems like if we used something like: https://mollyrocket.com/meowhash we could potentially speed up import hashing, since we import a fairly large amount of stuff for some builds.

however, we may have to do *both* kinds of hashing in some cases, since we allow users/content headers to do hash matching on sha256.

**Comment by tristanm-cisco** [comment]
After looking at this for a while, I'm not sure that meowhash is a great choice for general content addressable storage use cases.  While it performs wonderfully against smhasher, and was considered a possible level 3 hash initially, subsequent cryptanalysis revealed some deep issues.

https://peter.website/meow-hash-cryptanalysis

Differential cryptanalysis reveals a maximum 2^45 time complexity for collisions, degrading it to a level 1 hash, putting it in the range of CRC-64.  While this is acceptable for molly rocket's use case which hashes a static set of resources per release, hashes only strings of of resource names AFAIK, and probably includes error detection on most collisions, max 2^45 complexity for collisions is a little tight IMO for a content addressable storage use case.

Additionally, golang implementations of meowhash appear to lag the C implementation.  This is particularly true in hash speed of small payloads, where we would most expect to see wins, as where it lags is the optimization put to prologue/epilogue of the pipelined hash loop.

Additionally, as you've stated, in quite a few cases, we expect sha256 to be needed anyway, and managing both hashes comes with quite a bit of complexity.

Not wanting to just say 'no', I looked for some low hanging fruit, leading to this PR which increases sha256 hash rate by 4x-8x over golang's implementation:  https://github.com/anuvu/stacker/pull/227

**Comment by tych0** [comment]
Yeah, +1 on "we have to do sha256 anyway", maybe I'll just close this for now.
