### ISSUE TITLE
stacker clean should remove subvolume

### ISSUE THREAD

**Issue by hallyn** [anuvu/stacker#27]
After stacker clean --all, roots/.working stays around, so rm -rf project or rm -rf roots fails until the user figures out how to btrfs subvolume delete roots/.working .  Is there any reason to keep that dir around if everything's been cleaned out?

**Comment by tych0** [comment]
It should unmount and delete everything. I've heard other complaints of this happening, so maybe it's best if we add some defensive code here? But a simple unmount should be enough.

**Comment by hallyn** [comment]
Oh, it's already supposed to do that?  Ok I'll look into it then, thanks.

**Comment by tych0** [comment]
Well, it doesn't explicitly delete subvolumes, but it does try to unmount things. I think it's because btrfs is wedged in the kernel, when Mihai saw this before the kernel didn't think that btrfs was mounted there, but things couldn't be removed either.

**Comment by hallyn** [comment]
Not following.  Are you saying there is a reason why stacker clean should not do the btrfs subvolume remove?

It's a detail that i don't think most users should need to do by hand.

**Comment by tych0** [comment]
I'm saying it's not necessary. We already unmount the whole filesystem, so the subvolumes should disappear. They don't because of a kernel bug.

**Comment by hallyn** [comment]
User doesn't care who's fault it is.  They'll hold it against stacker.  Can we just try a subvolume remove and ignore if it's already been removed?

**Comment by tych0** [comment]
Sure, patches welcome :)

**Comment by hallyn** [comment]
Excellent.
