### ISSUE TITLE
Verify hashsums of files imported over HTTP

### ISSUE THREAD

**Issue by andaaron** [anuvu/stacker#44]
Stacker should do a HTTP HEAD call check the shasum of the files imported using HTTP.
There are several cases:
- If the file is not in cache download it
- If the file is in cache and the shasum is missing skip the download
- If the file is in cache and the shasum is present in HTTP head and different from the file cached locally download the file
- If the file is in cache and the shasum is present in HTTP head and matching the file cached locally skip the download

I've successfully used the method below with Artifactory in the past.
```
// getRemoteFileHash returns Sha256 for a file stored on a web server
func getRemoteFileHash(remoteURL string) (string, error) {

	// Make a HEAD call on remote URL
	resp, err := http.Head(remoteURL)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	// Get Sha256 from header
	hash := resp.Header.Get("X-Checksum-Sha256")
	return hash, nil
}
```

**Comment by andaaron** [comment]
@hallyn I understood from @tych0 that your input is needed before proceeding here.

**Comment by hallyn** [comment]
I just want to make sure that I can do builds, say, on an airplane, with everything cached.  So you can either ignore Head errors (after all, you already downloaded it once), or take a stacker --remoteisland argument (--no-net, --private?) to say "don't do these checks".  That's fine with me.

**Comment by andaaron** [comment]
Fixed in https://github.com/anuvu/stacker/pull/56
