### ISSUE TITLE
'stacker unpack' errors out after build because cached results conflict with unpack location

### ISSUE THREAD

**Issue by mikemccracken** [anuvu/stacker#6]
Unpacking uses the same btrfs fs as building, so if you build then unpack with the same config, you'll get an error like `error: btrfs create: exit status 1: ERROR: target path already exists: /whatever`.

One option that makes sense - could have unpack just always use a different btrfs fs.
There's just a default value for build cache and a different default for unpacking.
If you unpack and there's an existing fs, error out, allow a '-f' flag to wipe it first, etc.

**Comment by tych0** [comment]
How about we unpack to the same btrfs, but prompt the user about deleting existing stuff (and we can do the proper cache invalidation at this time too). I'll definitely include a --yes option for scripting. Does that work?

**Comment by mikemccracken** [comment]
that works, yeah.

On Feb 13, 2018, at 6:14 AM, Tycho Andersen <notifications@github.com<mailto:notifications@github.com>> wrote:


How about we unpack to the same btrfs, but prompt the user about deleting existing stuff (and we can do the proper cache invalidation at this time too). I'll definitely include a --yes option for scripting. Does that work?

**Comment by tych0** [comment]
We don't have a `stacker unpack` command any more, so I don't think this is relevant? I'll close for now.
