### ISSUE TITLE
caching issue in stacker build

### ISSUE THREAD

**Issue by rchamarthy** [anuvu/stacker#70]
1. import a dir with one file in it in a stacker.yaml file
2. do a stacker build
3. touch a file in that dir
4. do a stacker build
5. remove the file in that you additionally created
6. do a stacker build, it reports found a cached layer
7. In fact it found the wrong cached layer, when you unpack you see the file you created in step 3 in the layer

**Comment by hallyn** [comment]
So definately a part of the problem is shown by this debug patch:

```
diff --git a/import.go b/import.go
index 844f412..f3e2b29 100644
--- a/import.go
+++ b/import.go
@@ -118,9 +118,11 @@ func importFile(imp string, cacheDir string) (string, error) {
        }

        for _, d := range diff {
+               fmt.Printf("diff entry: %v\n", d)
                switch d.Type() {
                case mtree.Missing:
-                       err := os.RemoveAll(path.Join(cacheDir, d.Path()))
+                       fmt.Printf("I will remove %s/%s/%s\n", cacheDir, path.Base(imp), d.Path())
+                       err := os.RemoveAll(path.Join(cacheDir, path.Base(imp), d.Path()))
                        if err != nil {
                                return "", errors.Wrapf(err, "couldn't remove missing import %s", path.Join(cacheDir, d.Path()))
                        }
```
The path being Removed() in the Missing case is wrong, it needs to put path.Base(imp) in front of d.Path(). But when I just fix that, then it crashes trying to re-create the .working.  So I'm not sure how I'm supposed to tell stacker that I've effectively added a new import.

**Comment by hallyn** [comment]
Oh, actually it did fix it.  i was mixing stacker versions.
