### ISSUE TITLE
stacker to setup and generate lxc config for build containers

### ISSUE THREAD

**Issue by rchamarthy** [anuvu/stacker#81]
We use stacker to build artifacts using the flag ‘build_only: true’ to build go code and c code, these artifacts are later consumed by layer builds. Stacker launches the containers and based on the stacker yaml bind mounts the entire source repo and executes the build commands like bazel build or make as specified by the stacker yaml file. Once the build commands are done, container just exits and all the processes in that pid namespace just dies. This is usually the behavior we need but in the case of build servers we will need a slightly different behavior.

Bazel for example runs extremely fast because it launches a server process in background when we run “bazel build” and then all subsequent commands/builds just connect to that server process and uses its cache in memory. Java particularly has a lag when it comes to launching the jvm and building its cache. So its desirable for the build server to wait around for a long period (few hours) before timing itself out and dying out of idleness. As long as builds are happening within that timeout the server lingers around with its hot cache and builds are super fast. When we run bazel natively we see this behavior but when we run with stacker since the build container terminates and all the processes with it terminate we are not able to take advantage of the bazel server and its caches. This is adding about 30sec overhead for each build.

Feature requests for stacker:

1. Setup the container rfs based on the stacker imports and binds
2. Generate the lxc config that will use this rfs
3. Cleanup option - not sure if this belongs to lxc itself or stacker

**Comment by hallyn** [comment]
Maybe Tycho already knows the details, but I feel like I'm missing something.  Are you asking for a single container to be built with the running jvm, and for the other Run sections to run in that container?  Or are you asking for one long-running container for the jvm and for new transient clean containers for the builds?  If the latter, then how should we specify what needs to be shared between the containers so that the jvm task can serve the build in the new container?

**Comment by rchamarthy** [comment]
> Maybe Tycho already knows the details, but I feel like I'm missing something. Are you asking for a single container to be built with the running jvm, and for the other Run sections to run in that container? Or are you asking for one long-running container for the jvm and for new transient clean containers for the builds? If the latter, then how should we specify what needs to be shared between the containers so that the jvm task can serve the build in the new container?

@hallyn - what i am asking for is to create the container config but not run it. My plan is to start the container once that will do all the setup/cache etc. and in reaction each build command for example "build go code" i will simply attach to this container using lxc-attach, run the command in the context of the build container. This way i have all my builds happening in a running container.

**Comment by hallyn** [comment]
Would it be cleaner to make this a feature of recursive builds?  So parent/stacker.yaml can define a layer/container, say 'bazel', which will run your bazel task;  and parent/child1/stacker.yaml and parent/child2/stacker.yaml can say parent: bazel.  A recursive stacker build will start bazel once, run all the child builds, and only then shut down bazel?

Or you actually want bazel to stick around across multiple builds?  (On dev machines - that wouldn't make sense on a jenkins build)

**Comment by tych0** [comment]
I think the goal is to make bazel stick around for multiple builds.

**Comment by tych0** [comment]
I think this should come in the form of a `stacker container-setup` command, which would do the rootfs setup using the normal cache and generate the LXC config in `$roots/$container_name/lxc.conf`, but not actually run anything.

**Comment by rchamarthy** [comment]
> Would it be cleaner to make this a feature of recursive builds? So parent/stacker.yaml can define a layer/container, say 'bazel', which will run your bazel task; and parent/child1/stacker.yaml and parent/child2/stacker.yaml can say parent: bazel. A recursive stacker build will start bazel once, run all the child builds, and only then shut down bazel?
> 
> Or you actually want bazel to stick around across multiple builds? (On dev machines - that wouldn't make sense on a jenkins build)

I want bazel to stick around so that i can build as many times as i would like with the exact same cache. That is the crux of the use case. This is not for jenkins its mainly for developers who would want to run a lot build actions as fast as they can, just like they do on the host. Even integrate these into their IDE/vim/emacs etc.
