### ISSUE TITLE
Build multiple layer-types in the same execution

### ISSUE THREAD

**Issue by andaaron** [anuvu/stacker#89]
In out particular use-case we build layers in both `tar` and `squashfs` formats. Currently we need to run separate commands.

It would be a great time saver to be able to build layer in both formats in the same command, so we don't have to wait for the same file system to be built twice.

Not sure how the layer naming would work, since the same layer would be built at least twice.

**Comment by mikemccracken** [comment]
I've been working on this off and on for a couple of weeks with tycho's help.

**Comment by andaaron** [comment]
Thanks. Ravi mentioned this a while back, and I only recently remembered about it.

**Comment by tych0** [comment]
This is implemented now.
