### ISSUE TITLE
How do you run a Stacker container?

### ISSUE THREAD

**Issue by chainhead** [anuvu/stacker#99]
Suppose, the dependency on `brtfs` is met, how do we run an image generated with `stacker build -f first.yaml`? `runc`? `docker`?

BTW, is that ಅನುವು or అనువు ?

**Comment by tych0** [comment]
You should be able to use any runtime that's OCI compliant as the
result is an OCI image (with multiple tags, one for each target that
has been built).

I'm not sure about the name, @rchamarthy can probably elaborate :)

**Comment by rchamarthy** [comment]
> Suppose, the dependency on `brtfs` is met, how do we run an image generated with `stacker build -f first.yaml`? `runc`? `docker`?
> 
> BTW, is that ಅನುವು or అనువు ?

Its అణువు - means atom :)
